// Package halalrandomstrings provides a human-readable random string generator.
package halalrandomstrings

import (
	crand "crypto/rand"
	_ "embed"
	"encoding/json"
	"fmt"
	"math/big"
	"math/rand"
	"os"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/charmbracelet/x/exp/ordered"
)

const (
	defaultPrefixThreshold = 0.2
	defaultSuffixThreshold = 0.2
	maxRetries             = 1000 // Increased max retries
)

//go:embed words.json
var defaultWordsData []byte

type Words struct {
	Categories map[string][]string `json:"categories"`
	Rules      []Rule              `json:"rules"`	
	Blocked    []string            `json:"blocked"`
}

type Rule struct {
	Pattern  []string `json:"pattern"`
	Template string   `json:"template"`
}

// Engine provides a thread-safe random string generator engine.
type Engine struct {
	mu         sync.RWMutex
	words      Words
	blockedSet map[string]struct{}
}

func (e *Engine) rebuildBlockedSetLocked() {
	e.blockedSet = make(map[string]struct{}, len(e.words.Blocked))
	for _, b := range e.words.Blocked {
		norm := strings.ToLower(strings.TrimSpace(b))
		norm = strings.ReplaceAll(norm, "_", "-")
		norm = strings.ReplaceAll(norm, " ", "-")
		norm = strings.ReplaceAll(norm, "'", "-")
		for strings.Contains(norm, "--") {
			norm = strings.ReplaceAll(norm, "--", "-")
		}
		norm = strings.Trim(norm, "-")
		if norm != "" {
			e.blockedSet[norm] = struct{}{}
		}
	}
}

// NewEngine creates an Engine using the given Words dataset.
func NewEngine(w Words) *Engine {
	e := &Engine{words: w}
	e.rebuildBlockedSetLocked()
	return e
}

// NewDefaultEngine creates an Engine populated from embedded words.json.
func NewDefaultEngine() (*Engine, error) {
	var w Words
	if len(defaultWordsData) > 0 {
		if err := json.Unmarshal(defaultWordsData, &w); err != nil {
			return nil, fmt.Errorf("failed to parse embedded words.json: %w", err)
		}
	}
	e := &Engine{words: w}
	e.rebuildBlockedSetLocked()
	return e, nil
}

var (
	defaultEngine *Engine
	words         Words // Populated by default from embedded words.json, overridable by LoadWords
)

func init() {
	var err error
	defaultEngine, err = NewDefaultEngine()
	if err != nil {
		panic(fmt.Sprintf("failed to parse embedded words.json: %v", err))
	}
	words = defaultEngine.words
}

// DefaultEngine returns the package-level default engine.
func DefaultEngine() *Engine {
	return defaultEngine
}

// LoadWords reads words.json from the specified path and populates the engine words.
func (e *Engine) LoadWords(filePath string) error {
	byteValue, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to open words.json: %w", err)
	}

	var newWords Words
	if err := json.Unmarshal(byteValue, &newWords); err != nil {
		return fmt.Errorf("failed to parse words.json: %w", err)
	}

	e.mu.Lock()
	e.words = newWords
	e.rebuildBlockedSetLocked()
	e.mu.Unlock()
	return nil
}

// LoadWords reads words.json from the specified path and updates defaultEngine and package-level words.
func LoadWords(filePath string) error {
	if err := defaultEngine.LoadWords(filePath); err != nil {
		return err
	}
	defaultEngine.mu.RLock()
	words = defaultEngine.words
	defaultEngine.mu.RUnlock()
	return nil
}

func (e *Engine) isSafeLocked(s string) bool {
	norm := strings.ToLower(strings.TrimSpace(s))
	norm = strings.ReplaceAll(norm, "_", "-")
	norm = strings.ReplaceAll(norm, " ", "-")
	norm = strings.ReplaceAll(norm, "'", "-")
	for strings.Contains(norm, "--") {
		norm = strings.ReplaceAll(norm, "--", "-")
	}
	norm = strings.Trim(norm, "-")
	if norm == "" {
		return true
	}

	tokens := strings.Split(norm, "-")
	n := len(tokens)
	for i := 0; i < n; i++ {
		var sb strings.Builder
		for j := i; j < n && j < i+4; j++ {
			if j > i {
				sb.WriteString("-")
			}
			sb.WriteString(tokens[j])
			phrase := sb.String()
			if _, blocked := e.blockedSet[phrase]; blocked {
				return false
			}
		}
	}
	return true
}

// IsSafe checks whether a string is safe against blocked words.
func (e *Engine) IsSafe(s string) bool {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.isSafeLocked(s)
}

func isSafe(s string) bool {
	return defaultEngine.IsSafe(s)
}

func (e *Engine) getCategoriesLocked() []string {
	keys := make([]string, 0, len(e.words.Categories))
	for k := range e.words.Categories {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// GenerateWithOptionsE returns random strings generated by the engine with explicit error reporting.
func (e *Engine) GenerateWithOptionsE(opts Options) ([]string, error) {
	e.mu.RLock()
	defer e.mu.RUnlock()
	engineWords := e.words

	if opts.Repeat < 1 {
		opts.Repeat = 1
	}
	opts.PrefixThreshold = ordered.Clamp(opts.PrefixThreshold, 0, 1)
	opts.SuffixThreshold = ordered.Clamp(opts.SuffixThreshold, 0, 1)

	if opts.Sep == "" {
		opts.Sep = "-"
	}

	if opts.MinWords < 1 {
		opts.MinWords = 5 // Default to 5 words
	}

	if opts.MaxWords < opts.MinWords {
		opts.MaxWords = 8 // Default to 8 words
	}

	// Validate categories once before generation loops
	var filteredRules []Rule
	if len(opts.Categories) > 0 {
		for _, cat := range opts.Categories {
			cat = strings.TrimSpace(cat)
			if _, exists := engineWords.Categories[cat]; !exists {
				return nil, fmt.Errorf("unknown category: %q (available: %s)", cat, strings.Join(e.getCategoriesLocked(), ", "))
			}
		}

		// Exact compound rule matching
		for _, rule := range engineWords.Rules {
			allCategoriesMatch := true
			for _, patternCategory := range rule.Pattern {
				found := false
				for _, selectedCategory := range opts.Categories {
					if patternCategory == strings.TrimSpace(selectedCategory) {
						found = true
						break
					}
				}
				if !found {
					allCategoriesMatch = false
					break
				}
			}
			if allCategoriesMatch {
				filteredRules = append(filteredRules, rule)
			}
		}

		// Dynamic single-category rule fallback if no compound rules match
		if len(filteredRules) == 0 {
			for _, cat := range opts.Categories {
				cat = strings.TrimSpace(cat)
				filteredRules = append(filteredRules, Rule{
					Pattern:  []string{cat},
					Template: fmt.Sprintf("{%s}", cat),
				})
			}
		}
	} else {
		filteredRules = engineWords.Rules
	}

	if len(filteredRules) == 0 {
		return nil, fmt.Errorf("no rules available for specified options")
	}

	r := make([]string, opts.Repeat)
	
	// Use math/rand for word selection (faster)
	var src *rand.Rand
	if opts.Seed == 0 {
		src = rand.New(rand.NewSource(time.Now().UnixNano()))
	} else {
		src = rand.New(rand.NewSource(opts.Seed))
	}

	for i := range r {
		for j := 0; j < maxRetries; j++ {
			var currentOutput string
			var currentWordCount int

			// Build the string iteratively
			for attempt := 0; attempt < maxRetries; attempt++ {
				// Pick a random rule from filtered rules
				rule := filteredRules[src.Intn(len(filteredRules))]

				// Generate the string based on the rule
				var replacerArgs []string
				for _, category := range rule.Pattern {
					categoryWords := engineWords.Categories[category]
					if len(categoryWords) == 0 {
						continue
					}
					word := categoryWords[src.Intn(len(categoryWords))]
					replacerArgs = append(replacerArgs, fmt.Sprintf("{%s}", category), word)
				}

				replacer := strings.NewReplacer(replacerArgs...)
				generated := replacer.Replace(rule.Template)
				generated = strings.ReplaceAll(generated, "'", opts.Sep)
				if opts.Sep != "-" {
					generated = strings.ReplaceAll(generated, "-", opts.Sep)
				}
				generated = strings.ToLower(strings.ReplaceAll(generated, " ", opts.Sep))
				for strings.Contains(generated, opts.Sep+opts.Sep) {
					generated = strings.ReplaceAll(generated, opts.Sep+opts.Sep, opts.Sep)
				}
				generated = strings.Trim(generated, opts.Sep)
				
				// Calculate word count of the generated part
				generatedWordCount := len(strings.Split(generated, opts.Sep))

				// Check if adding this rule would exceed MaxWords
				if currentWordCount + generatedWordCount > opts.MaxWords {
					// If we have enough words already, finalize this string
					if currentWordCount >= opts.MinWords {
						break // Break from inner building loop
					} else {
						// Not enough words yet, and this rule exceeds MaxWords. Reset and try again.
						currentOutput = ""
						currentWordCount = 0
						continue // Continue to next attempt in inner building loop
					}
				}

				// Append the generated part
				if currentOutput == "" {
					currentOutput = generated
				} else {
					currentOutput = currentOutput + opts.Sep + generated
				}
				currentWordCount = len(strings.Split(currentOutput, opts.Sep))

				// If we have enough words, and haven't exceeded MaxWords, we can break
				if currentWordCount >= opts.MinWords && currentWordCount <= opts.MaxWords {
					break // Break from inner building loop
				}
			}

			// Finalize the output if it meets criteria
			if currentWordCount >= opts.MinWords && currentWordCount <= opts.MaxWords {
				if e.isSafeLocked(currentOutput) {
					output := currentOutput
					if opts.IncludeRandomNumber {
						// Generate a consistent 4-digit random number [1000, 9999] that fits safely in 32-bit systems
						num, err := crand.Int(crand.Reader, big.NewInt(9000))
						var val int64
						if err != nil {
							val = (time.Now().UnixNano() % 9000) + 1000
						} else {
							val = num.Int64() + 1000
						}
						output = fmt.Sprintf("%s%s%d", currentOutput, opts.Sep, val)
					}

					r[i] = output
					break // Break from maxRetries loop
				}
			}
		}
	}

	for i, s := range r {
		if s == "" {
			return nil, fmt.Errorf("failed to generate valid string for index %d within retry limit", i)
		}
	}

	return r, nil
}

// GenerateWithOptions returns random strings generated by the engine.
func (e *Engine) GenerateWithOptions(opts Options) []string {
	r, _ := e.GenerateWithOptionsE(opts)
	return r
}

// Options are options to customize output.
type Options struct {
	// Whether to show occasional additional prefix and suffix content. This
	// increases possibilities but can make strings longer.
	PrefixThreshold float64
	SuffixThreshold float64

	// Number of strings to generate.
	Repeat int

	// Separator to use between words.
	Sep string

	// Seed for the random number generator.
	Seed int64

	// Minimum number of words in the generated string.
	MinWords int

	// Maximum number of words in the generated string.
	MaxWords int

	// Whether to include a random number at the end of the string.
	IncludeRandomNumber bool

	// List of categories to use for string generation.
	Categories []string
}

// Generate returns a random string.
func (e *Engine) Generate() string {
	return e.GenerateWithOptions(Options{
		Repeat:              1,
		IncludeRandomNumber: true,
	})[0]
}

// GenerateN returns n random strings.
func (e *Engine) GenerateN(n int) []string {
	return e.GenerateWithOptions(Options{
		Repeat:              n,
		IncludeRandomNumber: true,
	})
}

// GetCategories returns a sorted list of available categories.
func (e *Engine) GetCategories() []string {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return e.getCategoriesLocked()
}

// Generate returns a random string using the default engine.
func Generate() string {
	return defaultEngine.Generate()
}

// GenerateN returns a given number of random strings using the default engine.
func GenerateN(n int) []string {
	return defaultEngine.GenerateN(n)
}

// GenerateWithOptionsE generates results against the given options using the default engine with explicit error reporting.
func GenerateWithOptionsE(o Options) ([]string, error) {
	return defaultEngine.GenerateWithOptionsE(o)
}

// GenerateWithOptions generates results against the given options using the default engine.
func GenerateWithOptions(o Options) []string {
	return defaultEngine.GenerateWithOptions(o)
}

// GetCategories returns a sorted list of available categories.
func GetCategories() []string {
	return defaultEngine.GetCategories()
}